name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TOTAL_CODE_TIME: true
          SHOW_TIMEZONE: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_COMMIT: true
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: true
